import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Nathanaël Derousseaux",
  description: "I write code and manage cloud systems. Currently working as a cloud engineer at the University of Strasbourg, teaching part-time and developing web projects as an independent software engineer.",
  keywords: [
    "Nathanaël Derousseaux",
    "cloud engineer",
    "web developer",
    "full stack developer",
    "software engineer",
    "cloud computing",
    "University of Strasbourg",
    "teaching",
    "Next.js",
    "React",
    "TypeScript",
    "Tailwind CSS",
    "web development",
    "portfolio",
    "freelance developer",
    "independent developer",
    "cloud systems",
    "system administration",
    "DevOps",
    "mobile development",
    "Strasbourg",
    "France",
  ],
  authors: [{ name: "Nathanaël Derousseaux" }],
  openGraph: {
    title: "Nathanaël Derousseaux",
    description: "I write code and manage cloud systems. Currently working as a cloud engineer at the University of Strasbourg, teaching part-time and developing web projects as an independent software engineer.",
    type: "website",
    locale: "fr_FR",
  },
  robots: {
    index: true,
    follow: true,
  },
};